### ISSUE TITLE
DateTimePicker remains empty within grid details

### ISSUE THREAD

**Issue by chhorz** [vaadin/vaadin-flow-components#479]
Hi,

i am currently facing an issue while using a `DateTimePicker` within a details component of a `Grid`. The value is shown for a small amount of time but then the value will be reset.

Vaadin-Version: 14.4.4

vaadin-grid-flow: 4.3.4
vaadin-date-time-picker-flow: 1.2.3

_Grid with DateTimePicke as Details-Component:_
```
Grid<Test> grid = new Grid<>();
grid.addColumn(Test::getS).setHeader("Title");
grid.setDetailsVisibleOnClick(true);
grid.setItemDetailsRenderer(new ComponentRenderer<>(s -> {
	DateTimePicker picker = new DateTimePicker();
	picker.setValue(LocalDateTime.now());
	return picker;
}));
grid.setItems(new Test("One"), new Test("Two"));
```
_Test class for Grid:_
```
private class Test {
	private String s;

	public Test(String s) {
		this.s = s;
	}

	public String getS() {
		return s;
	}
}
```
_Frontend-UI:_
![datetimepicker_within_griddetails](https://user-images.githubusercontent.com/16685526/100876989-765eb380-34a8-11eb-93ae-4c773f0c3951.png)

The issue seems to be related to the `setValue` method of the `DateTimePicker`:
```
    @Override
    public void setValue(LocalDateTime value) {
        super.setValue(value);
        // Get the value from client after possible adjustment.
        // This is a workaround for infinite value change loop which can be
        // triggered when the field is set as read-only.
        // fixme(haprog) This workaround should probably be removed after this
        // is fixed: https://github.com/vaadin/vaadin-time-picker-flow/issues/77
        getElement().executeJs("return this.value;")
                .then(jsonValue -> super.setValue(
                        jsonValue.asString().isEmpty() ? null :
                                LocalDateTime.parse(jsonValue.asString())));
    }
```
While debugging the value is available after the `super.setValue(value);` call but will disappear after the JS calls.

Greeting
Christian

**Comment by incaseoftrouble** [comment]
Hi, I also have the same problem. This is issue should be fixed in the current version.

The issue already was brought up [here](https://github.com/vaadin/vaadin-time-picker-flow/issues/22) and fixed [here](https://github.com/vaadin/vaadin-time-picker-flow/pull/79) (but in an old repo). These changes are also present in this repo for the 17 and 18 version (see [here](https://github.com/vaadin/vaadin-flow-components/blob/17.0/vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js))

Any chance of backporting this? It seems to be a very local and simple change.
